User repository writed, but user search some bug
greensaleuz/greensaleuz-webapi pull request #21
Opened 2023-08-06 13:54 UTC by rustambekovich

searchda ozgina muammo borga oxhab tuyulyapti shuning uchun camentariyada turibda erta fikrlashib togirlab qoyaman

2023-08-06 18:34 UTC, rustambekovich commented
close #5 
close #21

2023-08-07 03:37 UTC, ShohruhUzDev commented on src/GreenSaleuz.DataAccess/Repositories/Users/UserRepository.cs
> +            await _connection.OpenAsync();
Add one empty  line

2023-08-07 03:38 UTC, ShohruhUzDev requested changes

2023-08-07 03:38 UTC, ShohruhUzDev commented on src/GreenSaleuz.DataAccess/Repositories/Users/UserRepository.cs
> +            return result;
Add empy line above return

2023-08-07 04:11 UTC, merged