SERVICE: Constant TimeHelper
greensaleuz/greensaleuz-webapi pull request #49
Opened 2023-08-07 16:21 UTC by rustambekovich

close #42

2023-08-07 17:56 UTC, SamandarYigitaliyev commented on src/GreenSaleuz.Service/Helpers/TimeHelper.cs
> +        return time;
return dan oldin enter tashlash kerak

2023-08-07 17:57 UTC, SamandarYigitaliyev reviewed
To'g'irlab qayta yuklang

2023-08-07 17:58 UTC, SamandarYigitaliyev requested changes
Clean code ga amal qling

2023-08-08 03:32 UTC, MrOOI approved these changes

2023-08-08 03:33 UTC, MrOOI approved these changes

2023-08-08 03:37 UTC, SamandarYigitaliyev approved these changes
To'g'irlanibdi

2023-08-08 03:40 UTC, merged

2023-08-08 03:41 UTC, MrOOI commented
Closes #49